### ISSUE TITLE
ARM Template add dependency VNET before VM NICs

### ISSUE THREAD

**Issue by bfrankMS** [azuredevcollege/trainingdays#107]
Deployment failed:

{
    "status": "Failed",
    "error": {
        "code": "InvalidResourceReference",
        "message": "Resource /subscriptions/a2ba2440-3367-4053-86aa-07bcecc57e6f/resourceGroups/rg-vnetpeering/providers/Microsoft.Network/virtualNetworks/VNET1/subnets/VMSubnet1 referenced by resource /subscriptions/a2ba2440-3367-4053-86aa-07bcecc57e6f/resourceGroups/rg-vnetpeering/providers/Microsoft.Network/networkInterfaces/VMonVNET1-nic1 was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.",
        "details": []
    }
}

**Comment by cdennig** [comment]
Hi @AndreasM009, kannst Du hier mal einen Blick drauf werfen?

**Comment by bfrankMS** [comment]
Da ich das template verbrochen habe würde ich das auch fixen wollen. Das issue war eine errinnerung für mich. 😉
Ok?
Grüße
B

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by cdennig** [comment]
Ja, sorry. Hab den Kommentar wieder gelöscht. War im falschen Issue unterwegs :)
