### ISSUE TITLE
Rework of Day 3 content / challenges

### ISSUE THREAD

**Issue by cdennig** [azuredevcollege/trainingdays#145]
We should do a rework of day 3 based on the feedback from participants:

- focus more on CosmosDB + Cognitive Services (? - TBD: we have a dedicated day for it in the AI DevCollege)
- TBD: skip CosmosDB challenges at all and just do demos? Make the challenges optional?
- remove Azure Data Factory: push data to CosmosDB via code or prepare files for uploading to a db
- show how to use different APIs of CosmosDB (SQL + MongoDB + Gremlin - maybe let participants decide which one to test-drive?)
- TBD: add demo for CAP/PACELC theorem? 
- TBD: multi-master demo? Important to understand the impact on RTO/RPO
- show CosmosDB change feed. TBD: only in talk + optional challenge?
- remove or at least reduce challenge for Azure SQL DB (probably all participants have already dealt with SQL)
- TBD: reduce content for Azure Search to the minimum (e.g. make indexing documents an optional challenge and just mention the option in the talk?)

CC: @CodeUnicornMartha, @alschroe, @AndreasM009

**Comment by cdennig** [comment]
Agreed on:
- Reduce SQL: as bonus challenge --> dynamic data masking, accessmanagement, SQL Databace backup and retention policies
- Azure Search --> Remove NodeJS app. Example queries in portal. Link to document indexing.
- Azure Cognitve Services: Text + Translate. Reference AI Dev College
- CosmosDB: 
1. remove AzDataFactory
2. describe CAP/PACELC --> demo
3. multi-master --> demo (prio2)
4. RTO/RPO (prio2)
5. data modelling / denormalization
6. changefeed/changestreams

**Comment by CodeUnicornMartha** [comment]
• Intro anhand der Slides und Doku überprüfen
	• Screenshots aktualisieren - Cosmos anlegen
	• Add Data to Cosmos rausnehmen - NEU
	• Understanding Partitioning - 2 Beispiel Requests im Portal
	• Mit und Ohne - Queries
	• ARM TEMPLATE RAUS oder BICEP (OPTIONAL)
	• Integrate Cosmos DB into a Node.js App - RAUS
	• Eigene Application Screenshots (OPTIONAL)?
	• Datafactory RAUS


	1. Anlegen Cosmos
	2. Cloud Shell Add Data to Cosmos Integrate Node JS APP
	3. Queries Partitioning
	4. Change Feed
	5. Ende - Links zu Docs
	6. Code Beispielen (siehe Tag 2 - Challenges/Break Outs)
	7. Verweis auf Code Samples
