### ISSUE TITLE
Use CAF naming conventions for Azure Service Bus topics and subscriptions.

### ISSUE THREAD

**Issue by AndreasM009** [azuredevcollege/trainingdays#233]
Publisher, subscriber and queue consumer use topic and subscription name hard coded:
- SCM Indexer Function
- SCM Image Resizer
- SCM VisitReport
- SCM TextAnalytics

We need to change the names in Challenges of day3.

**Comment by AndreasM009** [comment]
Names are renamed as follows:

Topics and Subscriptions:

- Contacts Topic
   scmtopic -> sbt-contacts
- Contacts Topic subscribers
   contactsearch
   visitreports
- Visitreport Topic
   scmvrtopic -> sbt-visitreports
- Visitreport Subscribers
   scmvisitreporttextanalytics -> textanalytics
- Resource Queue
   thumbnails -> sbq-scm-thumbnails

**Comment by AndreasM009** [comment]
It is better not to change the names for day2 and day3. As we start from scratch on Day4 names should only be changed there.

**Comment by AndreasM009** [comment]
After a call with Christian, we decided to follow the Azure naming conventions in all challenges for all days.

**Comment by cdennig** [comment]
The Linux web app (visitreports) will now also be deployed to the scm-breakout-rg resource group. Only the textanalytics function needs to be created in a separate rg. 

#192
