### ISSUE TITLE
VSCode Azure Repos extension is deprecated

### ISSUE THREAD

**Issue by eizedev** [azuredevcollege/trainingdays#91]
Hi,

on day4 in [Commit the changes to your local branch](https://github.com/azuredevcollege/trainingdays/blob/master/day4/challenges/challenge-2.md#commit-the-changes-to-your-local-branch) you point out that you can use the VSCode extension **Azure repos**. However, this has been deprecated and is therefore no longer available in the VSCode Marketplace and is no longer actively developed. I think you should change or remove this reference.

[More Info](https://github.com/microsoft/azure-repos-vscode/blob/master/DEPRECATED.md)

Thanks, 
René

**Comment by cdennig** [comment]
Hi @AndreasM009, kannst Du hier mal einen Blick drauf werfen?

**Comment by AndreasM009** [comment]
Alles klar, schau ich mir an
